# Data sources

This data comes from a study designed and run by Megan, who is also a PhD student in the Psychology Department. We confirmed with Professor Robbins that using this dataset is appropriate for the EDAV course. In the study, multiple people to provides ratings of how ‘stressed’ and ‘overwhelmed’ they would be in each of 60 vignettes designed to range in ‘objective’ stress. 

In generating the vignettes of stressful events, we used the Daily Inventory of Stressful Events coding scheme. This scheme trains objective coders to rate each vignette. Two coders were trained and rated each vignette according to the DISE scheme; specifically how ‘objectively’ severe the stressor is from 0=not at all to 4=extremely, the life domain that the stressor falls into (i.e. home, work, etc), whether the stressor was chronic, whether it was a continuation of a stressor from a previous day, and whether the focus of involvement for the stressor was the self or someone else (i.e. a close family member).

To collect the data, 157 undergraduate students at Columbia participated for course credit. The study took place in 3 parts: 1) a 15-minute pre-study baseline survey, 2) study session one, and 3) study session two. The baseline survey assessed relevant psychological constructs such as loneliness, chronic stress experiences, and stress mindsets, in addition to demographic variables such as participant year in school, race, family income, etc. The second part consisted of meeting a trained research assistant online via Zoom. Participants first provided informed consent, then completed 3 brief mood questionnaires (Profile of Mood States; assessing current mood, mood during COVID, and mood in general in their life), followed by responding to each of the 60 vignettes. Upon hearing the research assistant read each vignette out loud, participants indicated: 1) how ‘stressed’ they would be from 0=not at all to 4=extremely, 2) how ‘overwhelmed’ they would be from 0=not at all to 4= extremely, 3) whether they had experienced something like the event described in the vignette with 1=yes and 0=no 4) whether it was easy to imagine themselves in the scenario described in the vignette with 1=yes and 0= no.

All data was therefore collected online via Qualtrics and it is all self-report survey data. The different data files contain different types of variables; either between-stressor measures of the vignettes (i.e. the objective codes), between-person measures of psychological traits and demographics (i.e. baseline data), or within-person stressor measures (i.e. the session 1 and session 2 data).

Due to the nature of the study (i.e. Columbia students filling out the surveys for course credit), there is very little missingness and few errors. The only errors that we did find (and not resolve!) was that three of the vignettes had more questions than they were supposed to. We opted to simply remove those vignettes from analysis for the purpose of this project.

