# Conclusion

Overall, our exploratory and data visualization efforts revealed several critial insights. In our ridge plots, we found a disparity between subjective stress responses to the scenarios and objective coder ratings of the scenarios. We found that these disparities were greatest for the low-end objective stressors and most variable for the mid-range objective stressors. Together, these findings suggest that stress reactivity is a subjective process and that future research should acknowledge it as such. In our mosaic plot, we found some interesting patterns related to the life domain that a stressor falls into, with discrimination events and financial events being the most consensually stressful. Next, our parallel coordinate plots did not reveal too many interesting patterns with repspect to stress reactivity. There was some clustering for gender such that women were generally more stress reactive than men (which aligns with previous research in this area) but no real effects of loneliness, close relationships, or socioeconomic status. Future efforts include running these hypotheses about individual differences into a formal statistical model. Our last static visualization was the box and whisker plot, which revealed some outliers in the proportion of participants that had not experienced something like the stressor before and who found it difficult to imagine themselves in the scenarios. Finally, our interactive plot revealed differences in subjective stress for each life category and how that varies from the first and second session of the study.

We have some limitations with our data in three aspects that we could take into account for future directions: 
1) We only have 157 students complete the survey with valid amount of answers, which might be relatively small. With more data, we will have more accurate output on some visualizations. 
2) The fact that only Columbia undergraduate students took the survey might lead to somewhat bias on individual factors such as income or family backgrounds. 
3) We have relatively large proportions (~25%) of missing data for columns like father education and mother education, which has weakened our analysis on these two factors by certain degree.

We learnt a lot about data visualization tools and methods from this class. By completing this final project, we even learned more about all the concepts and gained better insight into how we can use different types of graphs to conduct analyses on real-world data. We also have a better understanding for utilizing D3.js as well as HTML/CSS to produce interactive data visualization on web pages. All in all, it has been great fun to work out graphs and analysis by using different languages such as R, Python and HTML/JavaScript that we learnt from this EDAV class! :)
